remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache

locale: "en-US"
title: "My academic webpage"
name: "Kellen Donahue"
description: "A personal academic website demonstration"
url: "https://donahuekellen.github.io"
search: true
logo: "/assets/images/kellen.jpg"
author:
  name		: "Kellen Donahue"
  avatar	: "/assets/images/kellen.jpg"
  bio		: "I am a Graduate Student of Computer Science at the University of Montana"
  location	: "UM"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
  
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
include:
  - _pages
  - _posts

paginate: 5
paginate_path: /page:num/

